server:
  port: 9347
  root-folder: storage
  compression:
    enabled: true
    mime-types: application/json,application/pdf,application/zip
spring:
  datasource:
    url: jdbc:mysql://103.183.112.133:4307/tst_digitization_dev?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: digitization_dev1
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  data:
    redis:
      #spring.data.redis.use-redis-cache
#      use-redis-cache: false
      host: ${REDIS_HOST:103.183.112.133}
      port: ${REDIS_PORT:6379}  # Default to 6379 if not provided
api:
  prefix: /api/v1
jwt:
  expiration: 84000 #24 hours = 60 * 60 * 24
  expiration-refresh-token: 90000 #25 hours = 60 * 60 * 25
  secretKey: Kxxb9zA91Vz7IQ/pHuID1+xHkekZ9tBqYAorv7ghNSc=

logging:
  level:
    org:
      springframework.security: DEBUG

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  paths-to-match: /api/**
  show-actuator: true

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"
